import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';

export async function POST(request: NextRequest) {
  try {
    const { code, componentName } = await request.json();

    // Create ZIP file with all generated code
    const zip = new JSZip();

    // Add each file to the ZIP
    Object.entries(code).forEach(([filename, content]) => {
      zip.file(filename, content as string);
    });

    // Add README with instructions
    zip.file(
      'README.md',
      `# ${componentName}\n\nGenerated by QuickClone\n\n## Installation\n\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Development\n\n\`\`\`bash\nnpm run dev\n\`\`\`\n\n## Build\n\n\`\`\`bash\nnpm run build\n\`\`\``
    );

    // Generate ZIP buffer
    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer' });

    // Return ZIP file
    return new NextResponse(zipBuffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${componentName}.zip"`
      }
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: 'Failed to export code' },
      { status: 500 }
    );
  }
}
